name: Rust

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust Release binary
        # You may pin to the exact commit or the version.
        # uses: rust-build/rust-build.action@6febf1b0ed6499a46610b58ef9d810398e75f3c2
      uses: rust-build/rust-build.action@v1.4.5
      with:
        # Output target
        RUSTTARGET: aarch64-apple-darwin
